# Generated by Django 3.0.2 on 2020-02-10 03:10

from django.db import migrations, models
import user_profile.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institute', models.CharField(max_length=300)),
                ('level', models.CharField(max_length=50)),
                ('faculty', models.CharField(max_length=300)),
                ('start_date', models.DateField(validators=[user_profile.models.validate_education_date])),
                ('ongoing', models.BooleanField(default=False)),
                ('completion_date', models.DateField(validators=[user_profile.models.validate_education_date])),
            ],
        ),
    ]
